# Generated by Django 4.1.2 on 2022-10-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
